apiVersion: apps/v1
kind: Deployment
metadata:
  name: nano35-identity-api
  namespace: nano35
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nano35-identity-api
  template:
    metadata:
      labels:
        app: nano35-identity-api
    spec:
      containers:
        - name: nano35-identity-api
          image: bushemi2021/nano35.identity.api:latest
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nano35-identity-consumers
  namespace: nano35
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nano35-identity-consumers
  template:
    metadata:
      labels:
        app: nano35-identity-consumers
    spec:
      containers:
        - name: nano35-identity-consumers
          image: bushemi2021/nano35.identity.consumers:latest
---
apiVersion: v1
kind: Service
metadata:
  name: nano35-identity-entrypoint
  namespace: nano35
spec:
  type: NodePort
  selector:
    app: nano35-identity-api
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30100