apiVersion: apps/v1
kind: Deployment
metadata:
  name: nano35-serviceclient
  namespace: nano35
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nano35-serviceclient
  template:
    metadata:
      labels:
        app: nano35-serviceclient
    spec:
      containers:
      - image: bushemi2021/nano35serviceclient:latest
        name: nano35-serviceclient
        ports:
        - containerPort: 80
      restartPolicy: Always
      
---

apiVersion: v1
kind: Service
metadata:
  namespace: nano35
  name: nano35-serviceclient-svc
spec:
  type: NodePort
  ports:
    - port: 8000
      targetPort: 80
      nodePort: 32000
  selector:
    app: nano35-serviceclient
